/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.hotelbooking.system;

import java.util.Date;
import java.time.LocalDate;
import java.time.ZoneId;

/**
 *
 * @author Naz
 */
public class BookingDatePage extends javax.swing.JFrame {

    /**
     * Creates new form BookingDatePage
     */
    public BookingDatePage() {
        initComponents();
        this.loggedAsLbl.setText(CustomerMainPage.loggedAsMsg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLbl = new javax.swing.JLabel();
        loggedAsLbl = new javax.swing.JLabel();
        startBookingDateSpnnr = new javax.swing.JSpinner();
        lstBkngLbl = new javax.swing.JLabel();
        lstBookingDateSpnnr = new javax.swing.JSpinner();
        srtBkngLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLbl.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        instructionLbl.setText("Please choose the date that you want to book for");

        loggedAsLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loggedAsLbl.setText("Ya shall not have see tis :>");

        startBookingDateSpnnr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        startBookingDateSpnnr.setModel(new javax.swing.SpinnerDateModel());
        javax.swing.JSpinner.DateEditor dateEditorStrt = new javax.swing.JSpinner.DateEditor(startBookingDateSpnnr, "dd/MM/yyyy");
        startBookingDateSpnnr.setEditor(dateEditorStrt);

        lstBkngLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstBkngLbl.setText("Last Booking Date");

        lstBookingDateSpnnr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lstBookingDateSpnnr.setModel(new javax.swing.SpinnerDateModel());
        javax.swing.JSpinner.DateEditor dateEditorLst = new javax.swing.JSpinner.DateEditor(lstBookingDateSpnnr, "dd/MM/yyyy");
        lstBookingDateSpnnr.setEditor(dateEditorLst);

        srtBkngLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srtBkngLbl.setText("Start Booking Date");

        nextBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loggedAsLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(instructionLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lstBkngLbl)
                            .addComponent(startBookingDateSpnnr)
                            .addComponent(lstBookingDateSpnnr, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(srtBkngLbl)
                            .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loggedAsLbl)
                .addGap(58, 58, 58)
                .addComponent(instructionLbl)
                .addGap(60, 60, 60)
                .addComponent(srtBkngLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startBookingDateSpnnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lstBkngLbl)
                .addGap(3, 3, 3)
                .addComponent(lstBookingDateSpnnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(nextBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CustomerMainPage customerMainPage = new CustomerMainPage(CustomerMainPage.customer);
        this.setVisible(false);
        customerMainPage.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        Date strtDate = (Date) this.startBookingDateSpnnr.getValue();
        LocalDate strtLclDate = strtDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        Date lstDate = (Date) this.lstBookingDateSpnnr.getValue();
        LocalDate lstLclDate = lstDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        RoomBookingPage bkingPage = new RoomBookingPage(strtLclDate, lstLclDate);
        this.setVisible(false);
        bkingPage.setVisible(true);
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingDatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingDatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingDatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingDatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingDatePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel instructionLbl;
    private javax.swing.JLabel loggedAsLbl;
    private javax.swing.JLabel lstBkngLbl;
    private javax.swing.JSpinner lstBookingDateSpnnr;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel srtBkngLbl;
    private javax.swing.JSpinner startBookingDateSpnnr;
    // End of variables declaration//GEN-END:variables
}
