/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.hotelbooking.system;

/**
 *
 * @author Naz
 */
public class InvoicePage extends javax.swing.JFrame {

    Invoice invoice;
    /**
     * Creates new form ReceiptPage
     */
    public InvoicePage(Invoice invoice) {
        this.invoice = invoice;
        initComponents();
        
        this.startDateLbl.setText("Starting Date: " + RoomBookingPage.booking.getStartDate().toString());
        this.endDateLbl.setText("End Date: " + RoomBookingPage.lstDate.toString());
        this.ChosenRoomLbl.setText("Room Chosen: " + RoomBookingPage.booking.getBookedRoom().toString());
        this.lunchLbl.setText("Lunch: " + LunchSelectPage.isLunch);
        
        int durationDays = (int)RoomBookingPage.booking.getBookingDuration().toDays();   
        double roomPrice = RoomBookingPage.booking.getBookedRoom().getPrice();
        
        this.totalLbl.setText(String.format("Total: RM%.2f", (double)durationDays * roomPrice + (LunchSelectPage.noPax * 14.00)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payType = new javax.swing.JComboBox<>();
        srtBkngLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        startDateLbl = new javax.swing.JLabel();
        endDateLbl = new javax.swing.JLabel();
        ChosenRoomLbl = new javax.swing.JLabel();
        lunchLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        payType.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        payType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));

        srtBkngLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srtBkngLbl.setText("Payment Method");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Checkout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        startDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        startDateLbl.setText("Starting Date: ");

        endDateLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        endDateLbl.setText("Ending Date: ");

        ChosenRoomLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChosenRoomLbl.setText("Room Chosen: ");

        lunchLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lunchLbl.setText("Lunch: Yes or No <-- modify ni dan atas dalam constructor");

        totalLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        totalLbl.setText("Total: RM%.2f");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLbl)
                    .addComponent(lunchLbl)
                    .addComponent(ChosenRoomLbl)
                    .addComponent(endDateLbl)
                    .addComponent(startDateLbl)
                    .addComponent(srtBkngLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(payType, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289)
                        .addComponent(jButton1)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(startDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChosenRoomLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lunchLbl)
                .addGap(18, 18, 18)
                .addComponent(totalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(srtBkngLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(payType.getSelectedItem().equals("Card")){
            CardMethodPage myCMP = new CardMethodPage(invoice);
            myCMP.setVisible(true);
        }else{
            invoice.payByCash();
            ReceiptPage myrp = new ReceiptPage(invoice);
            myrp.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChosenRoomLbl;
    private javax.swing.JLabel endDateLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lunchLbl;
    private javax.swing.JComboBox<String> payType;
    private javax.swing.JLabel srtBkngLbl;
    private javax.swing.JLabel startDateLbl;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
